# Generated by Django 2.2.14 on 2020-07-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgdjangodemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
